### ISSUE TITLE
Gitter Chatroom to discuss about SHAREthem

### ISSUE THREAD

**Issue by karuppiah7890** [Sriharia/SHAREthem#1]
Create a gitter chatroom for this repository and link it accordingly.

We can discuss about the model used in SHAREthem and to make things more efficient!

**Comment by Sriharia** [comment]
Hey there. Apologies for the delay. Just created a chat room on gitter
https://gitter.im/SHAREthem/Lobby#

**Comment by karuppiah7890** [comment]
Cool ! :smile:
